# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4d5bc4b9cd4b2c3ae37061354ae9baf877709588e366b6c1ba01cac116bf902cd522a92be35f06bba25f006e9466718948358a7bab824924d39050e8569d35a

test:
  secret_key_base: e6b067e12f67a1179bc35eb68d3841c3948475dbe5e33146607c368606a052c2df6105c3a6703835e90ecda3d8a056a084924d53e266a28d66384d65905d19c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
